'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {planClientWorkCleanup}=require('../src/services/clientWorkCleanupService');
const actor={role:'ADMIN',userId:'admin'};
function fixture(){return {Leads:[{LeadID:'L1',ClientName:'Client',PrimaryMobile:'9876543210',SheetBasicRequirements:[{BudgetMax:30000}],Tags:['Duplicate Number'],NextFollowUpAt:'tomorrow'}],Transactions:[{TransactionID:'T1',LeadID:'L1'},{}],Requirements:[{RequirementID:'R1',TransactionID:'T1'}],FollowUps:[{LeadID:'L1',TransactionID:'T1'}],Activities:[{LeadID:'L1'}],Timeline:[{LeadID:'L1'}],Documents:[{LeadID:'L1'},{PropertyID:'P1'}],Inventory:[{PropertyID:'P1'}],Projects:[{ProjectID:'B1'}],Users:[{UserID:'admin'}],_V2Counters:{Transaction:200}};}
test('cleanup preserves contacts/source data/inventory and removes work including malformed rows',()=>{const db=fixture();const original=structuredClone(db);const p=planClientWorkCleanup(db,{action:'cleanup'},actor);assert.deepEqual(db,original);for(const k of ['Transactions','Requirements','FollowUps','Activities','Timeline'])assert.equal(p.next[k].length,0);assert.equal(p.next.Leads.length,1);assert.deepEqual(p.next.Leads[0].SheetBasicRequirements,db.Leads[0].SheetBasicRequirements);assert.equal(p.next.Leads[0].PrimaryMobile,db.Leads[0].PrimaryMobile);assert.deepEqual(p.next.Inventory,db.Inventory);assert.deepEqual(p.next.Projects,db.Projects);assert.deepEqual(p.next._V2Counters,db._V2Counters);assert.equal(p.next.Documents.length,1);assert.ok(p.report.backupId);});
test('normal restore recovers exact data and refuses overwrite of later client work',()=>{const db=fixture();const p=planClientWorkCleanup(db,{action:'cleanup'},actor);const r=planClientWorkCleanup(p.next,{action:'restore',backupId:p.report.backupId},actor);for(const k of ['Leads','Transactions','Requirements','FollowUps','Activities','Timeline','Documents'])assert.deepEqual(r.next[k],db[k]);p.next.Transactions.push({TransactionID:'NEW'});assert.throws(()=>planClientWorkCleanup(p.next,{action:'restore',backupId:p.report.backupId},actor),/changed after/);});
test('preview token binds all work, backup, clients and actor',()=>{const db=fixture();const p=planClientWorkCleanup(db,{action:'cleanup'},actor);db.FollowUps.push({LeadID:'L1'});assert.notEqual(planClientWorkCleanup(db,{action:'cleanup'},actor).report.token,p.report.token);assert.throws(()=>planClientWorkCleanup(db,{action:'cleanup'},{role:'AGENT'}),/Administrator/);});
test('repeat cleanup does not create another backup',()=>{const p=planClientWorkCleanup(fixture(),{action:'cleanup'},actor);const r=planClientWorkCleanup(p.next,{action:'cleanup'},actor);assert.equal(r.report.changed,false);assert.equal(r.next.ClientWorkCleanupBackups.length,1);});
